Adding IO::Pty::Easy (source taken from CPAN site)

diff --git a/p4d-puppet-onchange b/p4d-puppet-onchange
--- a/p4d-puppet-onchange
+++ b/p4d-puppet-onchange
@@ -1,14 +1,24 @@
 #!/bin/sh
 
 # This script is not for invoking directly. It is for use in conjunction (as a "callback") with
-# git-diff-puppet: this script will be looking for the .tmp_git_diff file
+# p4d-puppet: this script will be looking for the .tmp_p4_diff file
 set -e
+set -x
 
-[[ ! -f .tmp_git_diff ]] && echo ".tmp_git_diff not found; i was probably invoked in error, aborting" && exit 1
-# diffing the current diff with the saved diff to see if we should re-show the git diff in tmux
-if ! git diff | diff - .tmp_git_diff > /dev/null; then
+[[ ! -f .tmp_p4_diff ]] && echo ".tmp_p4_diff not found; this script was probably invoked in error, aborting" && exit 1
+
+if p4 diff | diff - .tmp_p4_diff > /dev/null; then
+	exit 0 # exit cleanly on no change
+fi
+# else continue script (things have changed)
+
+# parse the diff to construct the list of files to watch
+# grep "====" .tmp_p4_diff | sed "s/^==== .* - \(.*\) ====$/\1/" | while read line; do
+
+# diffing the current diff with the saved diff to see if we should re-show the p4 diff in tmux
+if ! p4 diff | diff - .tmp_p4_diff > /dev/null; then
 	# the Ctrl+L here is for keeping the less output from drifting down on changes
-	# the enter after q is to ensure it does not break when running on shell to start with 
-	tmux send-keys -t git-diff-puppet q enter C-l "{ git status && git diff }" enter
-	git diff > .tmp_git_diff
+	# the enter after q is to ensure it does not break when running on shell to start with
+	tmux send-keys -t p4-diff-puppet q enter C-l "{ p4 status && p4 diff }" enter
+	p4 diff > .tmp_p4_diff
 fi
